import type { Metadata } from "next";
import './globals.scss';
import styles from './layout.module.scss';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <header className={styles.header}>
            <div className={styles.logo}>
              <img src="/logo.svg" alt="Logo" />
            </div>
            <div className={styles.auth}>
              <button className={styles.loginButton}>登录</button>
            </div>
          </header>

          <main className={styles.main}>
            {children}
          </main>

          <footer className={styles.footer}>
            <p>© 2024 您的公司名称 | ICP备案号：京ICP备XXXXXXXX号-X</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
